### ISSUE TITLE
Issue with widgetbox in Bokeh

### ISSUE THREAD

**Issue by GhsJahanmir** [CIMCB/cimcb#6]
Hi,
This repository is very useful. However, after installation of cimcb, when I tried to import it, I got the following error. 
I appreciate any suggestion to tackle with it.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\cimcb\__init__.py", line 3, in <module>
    from . import bootstrap
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\cimcb\bootstrap\__init__.py", line 2, in <module>
    from .BC import BC
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\cimcb\bootstrap\BC.py", line 7, in <module>
    from bokeh.layouts import widgetbox, gridplot, column, row, layout
ImportError: cannot import name 'widgetbox' from 'bokeh.layouts' (C:\ProgramData\anaconda3\Lib\site-packages\bokeh\layouts.py)

Best,

**Comment by MordicusEtCubitus** [comment]
I had the same issue when trying to run a bokeh v2 code with bokeh v3

The bokeh migration guide says: 

The WidgetBox model and associated convenience function widgetbox have been removed. Use row, column, and grid layouts instead.


See : https://github.com/bokeh/bokeh/wiki/Migration-Guides#remove-300

The answer is late but it may help any in their web search for the same issue
